import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { WeatherNav } from "./_components/weatherNav";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Weather forcast app",
  description: "Weather forcast app generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/devchallenges.png" sizes="any" />
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
